//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_L.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAll
    {
        public int userId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int songId { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public int duration { get; set; }
    }
}
